import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NavBar } from '@/components/navbar/NavBar2'
import {Footer} from '@/components/footer/footer'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Providers>
          <header >
            <NavBar></NavBar>
          </header>
          <main className="w-5/6 self-center justify-self-center">

            {children}
          </main>
        </Providers>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
